server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${NAME:postgres}
    password: ${PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        # format_sql: true
        hbm2ddl:
          auto: validate
          enabled: true
          database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  application:
    name: spring-metrics-consumer

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  kafka:
    bootstrapAddress: localhost:9092
    topic: metrics-topic
    groupId: metrics-group