server:
  port: 8761

spring:
  application:
    name: spring-metrics-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
